version: '3.8'

services:
  app:
    build:
      context: .
    container_name: my-laravael-app
    networks:
      - my_network
    volumes:
      - /c/Users/GR/Desktop/laravael:/var/www/html

    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:latest
    container_name: my-mysql-container
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"

networks:
  my_network:
    driver: bridge
